//--------------------------------------------------------------------------------------------------------------------------
// <copyright file="GlobalSuppressions.cs" company="Oscar Brouwer">
//     Copyright (c) Oscar Brouwer 2011. All rights reserved.
// </copyright>
// <summary>
//     Holds the project's suppressions.
// </summary>
//--------------------------------------------------------------------------------------------------------------------------

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "Enkoni.Framework.Entities.Repository`1.#CreateAndExpressionCore(Enkoni.Framework.ISpecification`1<!0>,Enkoni.Framework.ISpecification`1<!0>)", Justification = "This is an accepted type and the user will hardly ever see it")]
[assembly: SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "Enkoni.Framework.Entities.Repository`1.#CreateCustomExpressionCore(Enkoni.Framework.ISpecification`1<!0>)", Justification = "This is an accepted type and the user will hardly ever see it")]
[assembly: SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "Enkoni.Framework.Entities.Repository`1.#CreateLambdaExpressionCore(System.Linq.Expressions.Expression`1<System.Func`2<!0,System.Boolean>>)", Justification = "This is an accepted type and the user will hardly ever see it")]
[assembly: SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "Enkoni.Framework.Entities.Repository`1.#CreateLikeExpressionCore(System.Linq.Expressions.Expression`1<System.Func`2<!0,System.String>>,System.String)", Justification = "This is an accepted type and the user will hardly ever see it")]
[assembly: SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "Enkoni.Framework.Entities.Repository`1.#CreateNotExpressionCore(Enkoni.Framework.ISpecification`1<!0>)", Justification = "This is an accepted type and the user will hardly ever see it")]
[assembly: SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "Enkoni.Framework.Entities.Repository`1.#CreateOrExpressionCore(Enkoni.Framework.ISpecification`1<!0>,Enkoni.Framework.ISpecification`1<!0>)", Justification = "This is an accepted type and the user will hardly ever see it")]
[assembly: SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "Enkoni.Framework.Entities.Repository`1.#FindAllCore(System.Linq.Expressions.Expression`1<System.Func`2<!0,System.Boolean>>,Enkoni.Framework.SortSpecifications`1<!0>,System.Int32,Enkoni.Framework.Entities.DataSourceInfo)", Justification = "This is an accepted type and the user will hardly ever see it")]
[assembly: SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "Enkoni.Framework.Entities.Repository`1.#FindFirstCore(System.Linq.Expressions.Expression`1<System.Func`2<!0,System.Boolean>>,Enkoni.Framework.SortSpecifications`1<!0>,Enkoni.Framework.Entities.DataSourceInfo)", Justification = "This is an accepted type and the user will hardly ever see it")]
[assembly: SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "Enkoni.Framework.Entities.Repository`1.#FindFirstCore(System.Linq.Expressions.Expression`1<System.Func`2<!0,System.Boolean>>,Enkoni.Framework.SortSpecifications`1<!0>,Enkoni.Framework.Entities.DataSourceInfo,!0)", Justification = "This is an accepted type and the user will hardly ever see it")]
[assembly: SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "Enkoni.Framework.Entities.Repository`1.#FindSingleCore(System.Linq.Expressions.Expression`1<System.Func`2<!0,System.Boolean>>,Enkoni.Framework.Entities.DataSourceInfo)", Justification = "This is an accepted type and the user will hardly ever see it")]
[assembly: SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "Enkoni.Framework.Entities.Repository`1.#FindSingleCore(System.Linq.Expressions.Expression`1<System.Func`2<!0,System.Boolean>>,Enkoni.Framework.Entities.DataSourceInfo,!0)", Justification = "This is an accepted type and the user will hardly ever see it")]

[assembly: SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "Enkoni.Framework.Entities.Repository`1.#Enkoni.Framework.ISpecificationVisitor`1<!0>.CreateAndExpression(Enkoni.Framework.ISpecification`1<!0>,Enkoni.Framework.ISpecification`1<!0>)", Justification = "Intentionally implemented interface explicitely to keep the API clean")]
[assembly: SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "Enkoni.Framework.Entities.Repository`1.#Enkoni.Framework.ISpecificationVisitor`1<!0>.CreateCustomExpression(Enkoni.Framework.ISpecification`1<!0>)", Justification = "Intentionally implemented interface explicitely to keep the API clean")]
[assembly: SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "Enkoni.Framework.Entities.Repository`1.#Enkoni.Framework.ISpecificationVisitor`1<!0>.CreateLambdaExpression(System.Linq.Expressions.Expression`1<System.Func`2<!0,System.Boolean>>)", Justification = "Intentionally implemented interface explicitely to keep the API clean")]
[assembly: SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "Enkoni.Framework.Entities.Repository`1.#Enkoni.Framework.ISpecificationVisitor`1<!0>.CreateLikeExpression(System.Linq.Expressions.Expression`1<System.Func`2<!0,System.String>>,System.String)", Justification = "Intentionally implemented interface explicitely to keep the API clean")]
[assembly: SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "Enkoni.Framework.Entities.Repository`1.#Enkoni.Framework.ISpecificationVisitor`1<!0>.CreateOrExpression(Enkoni.Framework.ISpecification`1<!0>,Enkoni.Framework.ISpecification`1<!0>)", Justification = "Intentionally implemented interface explicitely to keep the API clean")]
[assembly: SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "Enkoni.Framework.Entities.Repository`1.#Enkoni.Framework.ISpecificationVisitor`1<!0>.CreateNotExpression(Enkoni.Framework.ISpecification`1<!0>)", Justification = "Intentionally implemented interface explicitely to keep the API clean")]

[assembly: SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "Enkoni.Framework.Entities.DatabaseSourceInfo.#SelectDbContext(Enkoni.Framework.Entities.DataSourceInfo)", Justification = "The parameter is checked through the Is*Specified method")]
[assembly: SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "Enkoni.Framework.Entities.DatabaseSourceInfo.#.ctor(System.Collections.Generic.Dictionary`2<System.String,System.Object>)", Justification = "Validation is done by the base constructor.")]
[assembly: SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "Enkoni.Framework.Entities.FileSourceInfo.#SelectMonitorSourceFile(Enkoni.Framework.Entities.DataSourceInfo)", Justification = "The parameter is checked through the Is*Specified method")]
[assembly: SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "Enkoni.Framework.Entities.FileSourceInfo.#SelectSourceFileInfo(Enkoni.Framework.Entities.DataSourceInfo)", Justification = "The parameter is checked through the Is*Specified method")]
[assembly: SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "Enkoni.Framework.Entities.FileSourceInfo.#SelectChangeCompleteTimeout(Enkoni.Framework.Entities.DataSourceInfo)", Justification = "The parameter is checked through the Is*Specified method")]
[assembly: SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "Enkoni.Framework.Entities.FileSourceInfo.#.ctor(System.Collections.Generic.Dictionary`2<System.String,System.Object>)", Justification = "Validation is done by the base constructor.")]
[assembly: SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "Enkoni.Framework.Entities.CsvFileSourceInfo.#SelectSourceFileEncoding(Enkoni.Framework.Entities.DataSourceInfo)", Justification = "The parameter is checked through the Is*Specified method")]
[assembly: SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "Enkoni.Framework.Entities.CsvFileSourceInfo.#.ctor(System.Collections.Generic.Dictionary`2<System.String,System.Object>)", Justification = "Validation is done by the base constructor.")]
[assembly: SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "Enkoni.Framework.Entities.CsvFileRepository`1.#ReadAllRecordsFromFile(System.IO.FileInfo,Enkoni.Framework.Entities.DataSourceInfo)", Justification = "Validation is done by the baseclass")]
[assembly: SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "Enkoni.Framework.Entities.CsvFileRepository`1.#WriteAllRecordsToFile(System.IO.FileInfo,Enkoni.Framework.Entities.DataSourceInfo,System.Collections.Generic.IEnumerable`1<!0>)", Justification = "Validation is done by the baseclass")]
[assembly: SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "Enkoni.Framework.Entities.XmlFileRepository`1.#ReadAllRecordsFromFile(System.IO.FileInfo,Enkoni.Framework.Entities.DataSourceInfo)", Justification = "Validation is done by the baseclass")]
[assembly: SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "Enkoni.Framework.Entities.XmlFileRepository`1.#WriteAllRecordsToFile(System.IO.FileInfo,Enkoni.Framework.Entities.DataSourceInfo,System.Collections.Generic.IEnumerable`1<!0>)", Justification = "Validation is done by the baseclass")]
[assembly: SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "Enkoni.Framework.Entities.ServiceSourceInfo.#SelectEndpointConfigurationName(Enkoni.Framework.Entities.DataSourceInfo)", Justification = "The parameter is checked through the Is*Specified method")]
[assembly: SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "Enkoni.Framework.Entities.ServiceSourceInfo.#SelectBinding(Enkoni.Framework.Entities.DataSourceInfo)", Justification = "The parameter is checked through the Is*Specified method")]
[assembly: SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "Enkoni.Framework.Entities.ServiceSourceInfo.#SelectRemoteAddress(Enkoni.Framework.Entities.DataSourceInfo)", Justification = "The parameter is checked through the Is*Specified method")]
[assembly: SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "Enkoni.Framework.Entities.ServiceSourceInfo.#.ctor(System.Collections.Generic.Dictionary`2<System.String,System.Object>)", Justification = "Validation is done by the base constructor.")]
[assembly: SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "Enkoni.Framework.Entities.MemorySourceInfo`1.#.ctor(System.Collections.Generic.Dictionary`2<System.String,System.Object>)", Justification = "Validation is done by the base constructor.")]
[assembly: SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "Enkoni.Framework.Entities.MemorySourceInfo.#SelectMemoryStore`1(Enkoni.Framework.Entities.DataSourceInfo)", Justification = "The parameter is checked through the Is*Specified method")]
[assembly: SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "Enkoni.Framework.Entities.Repository`1.#CreateCustomExpressionCore(Enkoni.Framework.ISpecification`1<!0>)", Justification = "The parameter is checked in the public method")]
[assembly: SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "1", Scope = "member", Target = "Enkoni.Framework.Entities.Repository`1.#CreateLikeExpressionCore(System.Func`2<!0,System.String>,System.String)", Justification = "The parameter is checked in the public method")]
[assembly: SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "Enkoni.Framework.Entities.Repository`1.#CreateAndExpressionCore(Enkoni.Framework.ISpecification`1<!0>,Enkoni.Framework.ISpecification`1<!0>)", Justification = "The parameter is checked in the public method")]
[assembly: SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "1", Scope = "member", Target = "Enkoni.Framework.Entities.Repository`1.#CreateAndExpressionCore(Enkoni.Framework.ISpecification`1<!0>,Enkoni.Framework.ISpecification`1<!0>)", Justification = "The parameter is checked in the public method")]
[assembly: SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "Enkoni.Framework.Entities.DatabaseRepository`1.#FindAllCore(System.Linq.Expressions.Expression`1<System.Func`2<!0,System.Boolean>>,Enkoni.Framework.SortSpecifications`1<!0>,System.Int32,Enkoni.Framework.Entities.DataSourceInfo)", Justification = "The parameter is checked in the public method")]
[assembly: SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "Enkoni.Framework.Entities.DatabaseRepository`1.#FindFirstCore(System.Linq.Expressions.Expression`1<System.Func`2<!0,System.Boolean>>,Enkoni.Framework.SortSpecifications`1<!0>,Enkoni.Framework.Entities.DataSourceInfo,!0)", Justification = "The parameter is checked in the public method")]
[assembly: SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "Enkoni.Framework.Entities.DatabaseRepository`1.#FindSingleCore(System.Linq.Expressions.Expression`1<System.Func`2<!0,System.Boolean>>,Enkoni.Framework.Entities.DataSourceInfo,!0)", Justification = "The parameter is checked in the public method")]
[assembly: SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "1", Scope = "member", Target = "Enkoni.Framework.Entities.Repository`1.#CreateLikeExpressionCore(System.Linq.Expressions.Expression`1<System.Func`2<!0,System.String>>,System.String)", Justification = "The parameter is checked in the public method")]
[assembly: SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "Enkoni.Framework.Entities.Repository`1.#CreateNotExpressionCore(Enkoni.Framework.ISpecification`1<!0>)", Justification = "The parameter is checked in the public method")]
[assembly: SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "Enkoni.Framework.Entities.Repository`1.#CreateOrExpressionCore(Enkoni.Framework.ISpecification`1<!0>,Enkoni.Framework.ISpecification`1<!0>)", Justification = "The parameter is checked in the public method")]
[assembly: SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "1", Scope = "member", Target = "Enkoni.Framework.Entities.Repository`1.#CreateOrExpressionCore(Enkoni.Framework.ISpecification`1<!0>,Enkoni.Framework.ISpecification`1<!0>)", Justification = "The parameter is checked in the public method")]
[assembly: SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "Enkoni.Framework.Entities.Repository`1.#FindAllCore(System.Linq.Expressions.Expression`1<System.Func`2<!0,System.Boolean>>,Enkoni.Framework.SortSpecifications`1<!0>,System.Int32,Enkoni.Framework.Entities.DataSourceInfo)", Justification = "The parameter is checked in the public method")]
[assembly: SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "Enkoni.Framework.Entities.Repository`1.#FindFirstCore(System.Linq.Expressions.Expression`1<System.Func`2<!0,System.Boolean>>,Enkoni.Framework.SortSpecifications`1<!0>,Enkoni.Framework.Entities.DataSourceInfo,!0)", Justification = "The parameter is checked in the public method")]
[assembly: SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "Enkoni.Framework.Entities.Repository`1.#FindSingleCore(System.Linq.Expressions.Expression`1<System.Func`2<!0,System.Boolean>>,Enkoni.Framework.Entities.DataSourceInfo,!0)", Justification = "The parameter is checked in the public method")]

[assembly: SuppressMessage("Microsoft.Design", "CA1063:ImplementIDisposableCorrectly", Scope = "member", Target = "Enkoni.Framework.Entities.Repository`1.#Dispose()", Justification = "The Microsoft reference implementation is wrong.")]

[assembly: SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity", Scope = "member", Target = "Enkoni.Framework.Entities.MemoryRepository`1.#SaveChangesCore(Enkoni.Framework.Entities.DataSourceInfo)", Justification = "The code is well documented and therefore fine.")]

[assembly: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "Db", Scope = "member", Target = "Enkoni.Framework.Entities.DatabaseRepository`1.#DbContext", Justification = "This naming follows the naming convention of the EntityFramework CF CTP-library")]

[assembly: SuppressMessage("Microsoft.Usage", "CA1816:CallGCSuppressFinalizeCorrectly", Scope = "member", Target = "Enkoni.Framework.Entities.Repository`1.#Dispose()", Justification = "The Microsoft reference implementation is wrong.")]

[assembly: SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "FileRepository", Scope = "member", Target = "Enkoni.Framework.Entities.FileRepository`1.#.ctor(Enkoni.Framework.Entities.DataSourceInfo)", Justification = "The spelling here is fine")]
[assembly: SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "EndsWith", Scope = "member", Target = "Enkoni.Framework.Entities.DatabaseRepository`1.#CreateLikeExpressionCore(System.Linq.Expressions.Expression`1<System.Func`2<!0,System.String>>,System.String)", Justification = "This is the name of the method")]
[assembly: SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "StartsWith", Scope = "member", Target = "Enkoni.Framework.Entities.DatabaseRepository`1.#CreateLikeExpressionCore(System.Linq.Expressions.Expression`1<System.Func`2<!0,System.String>>,System.String)", Justification = "This is the name of the method")]
[assembly: SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "businessrules", Scope = "member", Target = "Enkoni.Framework.Entities.Repository`1.#ExecuteBusinessRuleWithMultipleResults(System.String,System.Collections.Generic.IEnumerable`1<System.Object>)", Justification = "The spelling here is fine")]
[assembly: SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "businessrules", Scope = "member", Target = "Enkoni.Framework.Entities.Repository`1.#ExecuteBusinessRuleWithSingleResult(System.String,System.Collections.Generic.IEnumerable`1<System.Object>)", Justification = "The spelling here is fine")]
