//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enkoni.Framework.Serialization.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Enkoni.Framework.Serialization.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a valid value for Boolean..
        /// </summary>
        internal static string FormatExceptionInvalidBooleanValue {
            get {
                return ResourceManager.GetString("FormatExceptionInvalidBooleanValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a valid value for Char..
        /// </summary>
        internal static string FormatExceptionInvalidCharValue {
            get {
                return ResourceManager.GetString("FormatExceptionInvalidCharValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a valid value for DateTime..
        /// </summary>
        internal static string FormatExceptionInvalidDateTimeValue {
            get {
                return ResourceManager.GetString("FormatExceptionInvalidDateTimeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not correctly formatted..
        /// </summary>
        internal static string FormatExceptionInvalidFormatting {
            get {
                return ResourceManager.GetString("FormatExceptionInvalidFormatting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a valid value for {1}..
        /// </summary>
        internal static string FormatExceptionInvalidTypeValue {
            get {
                return ResourceManager.GetString("FormatExceptionInvalidTypeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument must be between {0} and {1}.
        /// </summary>
        internal static string GuardArgumentMustBeBetween {
            get {
                return ResourceManager.GetString("GuardArgumentMustBeBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument must be greater than {0}.
        /// </summary>
        internal static string GuardArgumentMustBeGreaterThan {
            get {
                return ResourceManager.GetString("GuardArgumentMustBeGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument must be greater than or equal to {0}.
        /// </summary>
        internal static string GuardArgumentMustBeGreaterThanOrEqualTo {
            get {
                return ResourceManager.GetString("GuardArgumentMustBeGreaterThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument must be lower than {0}.
        /// </summary>
        internal static string GuardArgumentMustBeLowerThan {
            get {
                return ResourceManager.GetString("GuardArgumentMustBeLowerThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument must be lower than or equal to {0}.
        /// </summary>
        internal static string GuardArgumentMustBeLowerThanOrEqualTo {
            get {
                return ResourceManager.GetString("GuardArgumentMustBeLowerThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument is not of the expected type.
        /// </summary>
        internal static string GuardArgumentMustBeOfType {
            get {
                return ResourceManager.GetString("GuardArgumentMustBeOfType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument must be a valid enum value.
        /// </summary>
        internal static string GuardArgumentMustBeValidEnum {
            get {
                return ResourceManager.GetString("GuardArgumentMustBeValidEnum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument must be a valid path.
        /// </summary>
        internal static string GuardArgumentMustBeValidPath {
            get {
                return ResourceManager.GetString("GuardArgumentMustBeValidPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument has an illegal type.
        /// </summary>
        internal static string GuardArgumentMustNotBeOfType {
            get {
                return ResourceManager.GetString("GuardArgumentMustNotBeOfType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument cannot be empty.
        /// </summary>
        internal static string GuardValueCannotBeEmpty {
            get {
                return ResourceManager.GetString("GuardValueCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a valid format string..
        /// </summary>
        internal static string InvalidOperationExceptionInvalidFormatString {
            get {
                return ResourceManager.GetString("InvalidOperationExceptionInvalidFormatString", resourceCulture);
            }
        }
    }
}
