//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enkoni.Framework.DataAnnotations.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Enkoni.Framework.DataAnnotations.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10;13;15;20;23;24;26;30;33;35;36;38;40;43;45;46;50;53;55;58;70;71;72;73;74;75;76;77;78;79;88;111;113;114;115;117;118;161;162;164;165;166;167;168;172;174;180;181;182;183;184;186;187;222;223;224;226;227;228;229;251;252;255;294;297;299;313;314;315;316;317;318;320;321;341;342;343;344;345;346;347;348;411;412;413;416;418;475;478;481;485;486;487;488;492;493;495;497;499;511;512;513;514;515;516;517;518;519;521;522;523;524;525;527;528;529;541;543;544;545;546;547;548;561;562;566;570;571;572;573;575;577;578;591;592;593 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AreaCodes_NL {
            get {
                return ResourceManager.GetString("AreaCodes_NL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^((((((\+|00)31(\(0\))?({0}))|(0({0})))-?)|(\(0({0})\)))[2-8]\d{{6}}|(((((\+|00)31(\(0\))?({1}))|(0({1})))-?)|(\(0({1})\)))[2-8]\d{{5}})$.
        /// </summary>
        internal static string RegularRegexPattern_NL {
            get {
                return ResourceManager.GetString("RegularRegexPattern_NL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^(((((0({0})))-?)|(\(0({0})\)))[2-8]\d{{6}}|((((0({1})))-?)|(\(0({1})\)))[2-8]\d{{5}})$.
        /// </summary>
        internal static string RegularRegexPatternNoCountryAccessCode_NL {
            get {
                return ResourceManager.GetString("RegularRegexPatternNoCountryAccessCode_NL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^((((16\d{{2}})|(10[0-5,7-9]\d{{2}}))?((((0({0})))-?)|(\(0({0})\)))[2-8]\d{{6}})|(((16\d{{2}})|(10[0-5,7-9]\d{{2}}))?((((0({1})))-?)|(\(0({1})\)))[2-8]\d{{5}}))$.
        /// </summary>
        internal static string RegularRegexPatternNoCountryAccessCodeWithCarrierPreselect_NL {
            get {
                return ResourceManager.GetString("RegularRegexPatternNoCountryAccessCodeWithCarrierPreselect_NL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^(((((((\+|(((16\d{{2}})|(10[0-5,7-9]\d{{2}}))?)00)31(\(0\))?({0}))|((((16\d{{2}})|(10[0-5,7-9]\d{{2}}))?)0({0})))-?)|((((16\d{{2}})|(10[0-5,7-9]\d{{2}}))?)\(0({0})\)))[2-8]\d{{6}})|((((((\+|(((16\d{{2}})|(10[0-5,7-9]\d{{2}}))?)00)31(\(0\))?({1}))|((((16\d{{2}})|(10[0-5,7-9]\d{{2}}))?)0({1})))-?)|((((16\d{{2}})|(10[0-5,7-9]\d{{2}}))?)\(0({1})\)))[2-8]\d{{5}}))$.
        /// </summary>
        internal static string RegularRegexPatternWithCarrierPreselect_NL {
            get {
                return ResourceManager.GetString("RegularRegexPatternWithCarrierPreselect_NL", resourceCulture);
            }
        }
    }
}
