using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Microsoft.Design", "CA1019:DefineAccessorsForAttributeArguments", Scope = "type", Target = "Enkoni.Framework.Serialization.CsvRecordAttribute", Justification = "The is a property, it is just of another type (string vs char)")]

[assembly: SuppressMessage("Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Scope = "member", Target = "Enkoni.Framework.Serialization.Serializer`1.#DeserializeToFileHelper(System.Object)", Justification = "The exception is stored and rethrown later on, so no harm's done")]
[assembly: SuppressMessage("Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Scope = "member", Target = "Enkoni.Framework.Serialization.Serializer`1.#DeserializeToStreamHelper(System.Object)", Justification = "The exception is stored and rethrown later on, so no harm's done")]
[assembly: SuppressMessage("Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Scope = "member", Target = "Enkoni.Framework.Serialization.Serializer`1.#SerializeToFileHelper(System.Object)", Justification = "The exception is stored and rethrown later on, so no harm's done")]
[assembly: SuppressMessage("Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Scope = "member", Target = "Enkoni.Framework.Serialization.Serializer`1.#SerializeToStreamHelper(System.Object)", Justification = "The exception is stored and rethrown later on, so no harm's done")]

[assembly: SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "Enkoni.Framework.Serialization.Serializer`1.#Serialize(System.Collections.Generic.IEnumerable`1<!0>,System.Text.Encoding,System.IO.Stream)", Justification = "The parameter is already checked in the public method")]
[assembly: SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "1", Scope = "member", Target = "Enkoni.Framework.Serialization.Serializer`1.#Serialize(System.Collections.Generic.IEnumerable`1<!0>,System.Text.Encoding,System.IO.Stream)", Justification = "The parameter is already checked in the public method")]
[assembly: SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "2", Scope = "member", Target = "Enkoni.Framework.Serialization.Serializer`1.#Serialize(System.Collections.Generic.IEnumerable`1<!0>,System.Text.Encoding,System.IO.Stream)", Justification = "The parameter is already checked in the public method")]
[assembly: SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "3", Scope = "member", Target = "Enkoni.Framework.Serialization.CsvTransformer`1.#FromBytesCore(System.Byte[],System.Int32,System.Int32,System.Text.Encoding)", Justification = "The parameter is already checked in the public method")]
[assembly: SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "Enkoni.Framework.Serialization.CsvTransformer`1.#FromBytesCore(System.Byte[],System.Text.Encoding)", Justification = "The parameter is already checked in the public method")]
[assembly: SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "Enkoni.Framework.Serialization.CsvTransformer`1.#FromStringCore(System.String)", Justification = "The parameter is already checked in the public method")]
[assembly: SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "1", Scope = "member", Target = "Enkoni.Framework.Serialization.CsvTransformer`1.#ToBytesCore(!0,System.Text.Encoding)", Justification = "The parameter is already checked in the public method")]
[assembly: SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "2", Scope = "member", Target = "Enkoni.Framework.Serialization.CsvTransformer`1.#ToBytesCore(!0,System.Text.Encoding,System.Byte[],System.Int32)", Justification = "The parameter is already checked in the public method")]

[assembly: SuppressMessage("Microsoft.Naming", "CA1720:IdentifiersShouldNotContainTypeNames", MessageId = "bytes", Scope = "member", Target = "Enkoni.Framework.Serialization.Transformer`1.#FromBytes(System.Byte[],System.Int32,System.Int32,System.Text.Encoding)", Justification = "This name is better self-explanatory than any other name.")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1720:IdentifiersShouldNotContainTypeNames", MessageId = "bytes", Scope = "member", Target = "Enkoni.Framework.Serialization.Transformer`1.#FromBytes(System.Byte[],System.Text.Encoding)", Justification = "This name is better self-explanatory than any other name.")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1720:IdentifiersShouldNotContainTypeNames", MessageId = "bytes", Scope = "member", Target = "Enkoni.Framework.Serialization.Transformer`1.#FromBytesCore(System.Byte[],System.Int32,System.Int32,System.Text.Encoding)", Justification = "This name is better self-explanatory than any other name.")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1720:IdentifiersShouldNotContainTypeNames", MessageId = "bytes", Scope = "member", Target = "Enkoni.Framework.Serialization.Transformer`1.#FromBytesCore(System.Byte[],System.Text.Encoding)", Justification = "This name is better self-explanatory than any other name.")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1720:IdentifiersShouldNotContainTypeNames", MessageId = "bytes", Scope = "member", Target = "Enkoni.Framework.Serialization.Transformer`1.#ToBytes(!0,System.Text.Encoding,System.Byte[],System.Int32)", Justification = "This name is better self-explanatory than any other name.")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1720:IdentifiersShouldNotContainTypeNames", MessageId = "bytes", Scope = "member", Target = "Enkoni.Framework.Serialization.Transformer`1.#ToBytesCore(!0,System.Text.Encoding,System.Byte[],System.Int32)", Justification = "This name is better self-explanatory than any other name.")]

[assembly: SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "CsvRecord-attribute", Scope = "member", Target = "Enkoni.Framework.Serialization.CsvTransformer`1.#.ctor()", Justification = "The spelling is correct")]
[assembly: SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "DeserializeFromFilePropertyContainer", Scope = "member", Target = "Enkoni.Framework.Serialization.Serializer`1.#DeserializeToFileHelper(System.Object)", Justification = "The spelling is correct")]
[assembly: SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "DeserializeFromStreamPropertyContainer", Scope = "member", Target = "Enkoni.Framework.Serialization.Serializer`1.#DeserializeToStreamHelper(System.Object)", Justification = "The spelling is correct")]
[assembly: SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "SerializeToFilePropertyContainer", Scope = "member", Target = "Enkoni.Framework.Serialization.Serializer`1.#SerializeToFileHelper(System.Object)", Justification = "The spelling is correct")]
[assembly: SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "SerializeToStreamPropertyContainer", Scope = "member", Target = "Enkoni.Framework.Serialization.Serializer`1.#SerializeToStreamHelper(System.Object)", Justification = "The spelling is correct")]